baseURL = "https://peterwangyong.github.io"
languageCode = "zh-CN"
title = "涌现"
author = "PeterWang"
builddrafts = false
theme = "hugo-uno"

[Params]
email = "peterwangyong@foxmail.com"
description = "万物之上，皆为涌现"
